# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60d523260be4e8b4131871f131bec5165df77faf229e04680ff4f188e96e5a9d0fb97d73e2695b275faac52863416696681981b7236c8664b86c2d5c8be1e9ae

test:
  secret_key_base: 3e2449c1bdf175f869e2c4781a71fa762a3761c9f486a4368c036ab2bb410ad74237179a8821218257f028f8a0d753f121d9d2333e73bb6e9c0321c91fa74113

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
